version: '3'
services:


  django-app:
    build:
      context: ./CrmBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306


  python-app:
    build:
      context: ./Services

      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - redis
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  mysql:
      image: mysql:8.0
      environment:

        MYSQL_ROOT_PASSWORD: 111111
        MYSQL_DATABASE: Crm
        MYSQL_USER: admin
        MYSQL_PASSWORD: 111111
      ports:
        - "3306:3306"
      restart: always

