version: '3'
services:


  django-app:
    build:
      context: ./CrmBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=111111



  python-app:
    build:
      context: ./Services

      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - redis
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  angular-app:
    build:
      context: ./CrmFront
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: always

    environment:
      - NODE_ENV=development

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  mysql:
      image: mysql:8.0
      environment:

        MYSQL_ROOT_PASSWORD: 111111
        MYSQL_DATABASE: Crm
        MYSQL_USER: admin
        MYSQL_PASSWORD: 111111
      ports:
        - "3306:3306"
      restart: always


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django-app
      - angular-app
    restart: always
