version: '4.7'
services:


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: Crm
      MYSQL_USER: admin
      MYSQL_PASSWORD: 111111
    ports:
      - "3306:3306"
    restart: always

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s



  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5



  django-app:
    build:
      context: ./CrmBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
          condition: service_healthy

    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=111111

  python-app:
    build:
      context: ./Services
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  angular-app:
    build:
      context: ./CrmFront
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "4200:4200"
    restart: always

    environment:
      - NODE_ENV=production

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
       - django-app
